import {describe,it,expect} from 'vitest'
import {createDefaultConfig,createRoom} from '../domain/defaults'
import {OPERATORS} from '../domain/operators'
import {analyzeControlImpact,compareControlConfigurations} from './controlImpact'
const id=(name:string)=>OPERATORS.find(o=>o.name===name)!.charId
function config(){const c=createDefaultConfig();c.rooms=[];c.controlOperatorIds=[];return c}
function trade(c:ReturnType<typeof config>,level:1|2|3=1,names:string[]=[]){const r=createRoom('T'+c.rooms.length,'trading');r.specialOrder='none';r.level=level;r.operatorIds=names.map(id);c.rooms.push(r);return r}
describe('static control opportunity comparison',()=>{
 it('projects Amiya +7 points as 280 score/day over two level-one ordinary trades',()=>{const c=config();trade(c);trade(c);c.controlOperatorIds=[id('阿米娅')];const r=analyzeControlImpact(c);expect(r.baseline.complete).toBe(true);expect(r.members[0]!.delta.daily.orderFaceValue).toBeCloseTo(1400);expect(r.members[0]!.delta.daily.score).toBeCloseTo(280);expect(r.members[0]!.delta.baseMoraleReductionPerHour).toBeCloseTo(.05)})
 it('does not add leave-one-out margins for identical maximum effects',()=>{const c=config();trade(c);c.controlOperatorIds=['阿米娅','诗怀雅'].map(id);const r=analyzeControlImpact(c);expect(r.members.map(x=>x.delta.daily.score)).toEqual([0,0]);expect(r.withoutAll.delta.daily.score).toBeCloseTo(140)})
 it('projects Kaltsit two gold and two EXP factories to 640 score/day',()=>{const c=config();for(let i=0;i<4;i++){const r=createRoom('M'+i,'manufacture');r.product=i<2?'gold':'exp';c.rooms.push(r)}c.controlOperatorIds=[id('凯尔希')];const r=analyzeControlImpact(c);expect(r.members[0]!.delta.daily.exp).toBeCloseTo(320);expect(r.members[0]!.delta.daily.goldValue).toBeCloseTo(400);expect(r.members[0]!.delta.daily.score).toBeCloseTo(640)})
 it('quantifies Delphine 20 points for Morgan Siege, with 35 named bonus only once',()=>{const c=config();trade(c,2,['摩根','推进之王']);c.controlOperatorIds=[id('戴菲恩')];const r=analyzeControlImpact(c);expect(r.baseline.rooms[0]!.efficiencyPercent).toBe(197);expect(r.members[0]!.without.rooms[0]!.efficiencyPercent).toBe(177);expect(r.members[0]!.delta.rooms[0]!.efficiencyPoints).toBe(20);expect(r.members[0]!.delta.daily.orderFaceValue).toBeCloseTo(1440*.2*1200/170.4)})
 it('compares actual replacements and leaves all input state unchanged',()=>{const c=config();trade(c,2,['摩根','推进之王']);c.controlOperatorIds=[id('阿米娅')];const before=structuredClone(c);const r=compareControlConfigurations(c,[id('戴菲恩')]);expect(r.delta.rooms[0]!.efficiencyPoints).toBe(13);expect(r.delta.baseMoraleReductionPerHour).toBe(0);expect(c).toEqual(before)})
 it('uses transformed Proviso reward rather than normal-order gross value',()=>{const c=config();trade(c,1,['但书']);c.controlOperatorIds=[id('阿米娅')];expect(analyzeControlImpact(c).members[0]!.delta.daily.orderFaceValue).toBeCloseTo(1400)})
 it('keeps Pepe fixed-time orders independent of control efficiency',()=>{const c=config();trade(c,1,['佩佩']);c.controlOperatorIds=[id('阿米娅')];const r=analyzeControlImpact(c);expect(r.members[0]!.delta.daily.orderFaceValue).toBe(0);expect(r.baseline.complete).toBe(true);expect(r.baseline.rooms[0]!.daily.orderFaceValue).toBeCloseTo(1440/270*1000)})
 it('retains unquantified rules instead of certifying incomplete scores',()=>{const c=config();trade(c,3,['铎铃']);c.controlOperatorIds=[id('阿米娅')];const r=analyzeControlImpact(c);expect(r.baseline.complete).toBe(false);expect(r.baseline.diagnostics.join(' ')).toContain('铎铃')})
 it('marks timed run-order projection unavailable without inventing immediate swaps',()=>{const c=config();trade(c).specialOrder='shiftRun';const r=analyzeControlImpact(c);expect(r.baseline.complete).toBe(false);expect(r.baseline.diagnostics.join(' ')).toContain('跑单')})
 it('separates charging efficiency from income and observes exhausted providers',()=>{const c=config();const p=createRoom('P','power');p.operatorIds=[id('埃癸斯')];c.rooms.push(p);c.controlOperatorIds=[id('凯尔希')];c.zeroMoraleOperatorIds=[id('凯尔希')];const r=analyzeControlImpact(c);expect(r.baseline.powerBonusPercent).toBe(20);expect(r.baseline.daily.score).toBe(0);expect(r.members[0]!.delta.baseMoraleReductionPerHour).toBe(0)})
 it('rejects duplicate or elsewhere-occupied replacement control operators',()=>{const c=config();trade(c,2,['摩根']);expect(()=>compareControlConfigurations(c,[id('摩根')])).toThrow();expect(()=>compareControlConfigurations(c,[id('阿米娅'),id('阿米娅')])).toThrow()})
 it('permits level 1 EXP recipe and retains excluded product diagnostics',()=>{const c=config();const m=createRoom('M','manufacture');m.level=1;m.product='exp';c.rooms=[m];expect(analyzeControlImpact(c).baseline.complete).toBe(true);m.level=3;m.product='fragment';expect(analyzeControlImpact(c).baseline.diagnostics.join(' ')).toContain('评分')})
})

describe('control projection preserves snapshot and cross-facility context',()=>{
 it('can show a dedicated supporter losing to a general control bonus',()=>{const c=config();trade(c,1,['能天使']);c.controlOperatorIds=[id('阿米娅')];const r=compareControlConfigurations(c,[id('戴菲恩')]);expect(r.delta.rooms[0]!.efficiencyPoints).toBe(-7);expect(r.delta.daily.score).toBeCloseTo(-140)})
 it('rebuilds virtual power sources rather than summing direct control percentages',()=>{const c=config();const m=createRoom('M','manufacture');m.operatorIds=[id('温蒂')];const p=createRoom('P','power');p.operatorIds=[id('Lancet-2')];c.rooms=[m,p];c.controlOperatorIds=[id('森蚺')];const r=analyzeControlImpact(c);expect(r.members[0]!.delta.rooms[0]!.efficiencyPoints).toBe(30);expect(r.members[0]!.delta.powerBonusPercent).toBe(0);expect(r.members[0]!.delta.daily.score).toBeCloseTo(2400)})
 it('respects explicit warmup time while keeping identical production snapshots in all counterfactuals',()=>{const c=config();const m=createRoom('M','manufacture');m.operatorIds=[id('芬')];c.rooms=[m];c.controlOperatorIds=[id('凯尔希')];const fresh=analyzeControlImpact(c,{timeContext:{workHoursByOperator:new Map([[id('芬'),0]])}});const warm=analyzeControlImpact(c,{timeContext:{workHoursByOperator:new Map([[id('芬'),5]])}});expect(warm.baseline.rooms[0]!.efficiencyPercent-fresh.baseline.rooms[0]!.efficiencyPercent).toBe(5);expect(fresh.members[0]!.delta.rooms[0]!.efficiencyPoints).toBe(2);expect(warm.members[0]!.delta.rooms[0]!.efficiencyPoints).toBe(2)})
 it('honors explicit zero morale even without the legacy exhausted list',()=>{const c=config();trade(c);c.controlOperatorIds=[id('阿米娅')];c.operatorMorale[id('阿米娅')]=0;const r=analyzeControlImpact(c);expect(r.baseline.activeControlCount).toBe(0);expect(r.members[0]!.delta.daily.score).toBe(0)})
 it('applies Tequila bonus to four-gold orders only, using expectation divided by expected duration',()=>{const c=config();trade(c,3,['龙舌兰']);c.controlOperatorIds=[id('阿米娅')];const r=analyzeControlImpact(c);expect(r.members[0]!.delta.daily.orderFaceValue).toBeCloseTo(1440*.07*(.3*1000+.5*1500+.2*2500)/(.3*144+.5*210+.2*276))})
})
