import {describe,it,expect} from 'vitest'
import {MOWER_TASK_TYPES as T,MowerTask,MowerTaskQueue,toMowerMicros} from './mowerTaskQueue'
describe('pinned Mower task queue contract',()=>{
 it('stably sorts equal times without inventing type priority',()=>{const q=new MowerTaskQueue();const a=new MowerTask({time:2,type:T.SHIFT_ON}),b=new MowerTask({time:2,type:T.RUN_ORDER}),c=new MowerTask({time:1,type:T.FIAMMETTA});q.tasks.push(a,b,c);q.sort();expect(q.tasks).toEqual([c,a,b])})
 it('uses strict less/greater and the original 1.5-second equality window',()=>{const q=new MowerTaskQueue(),task=new MowerTask({time:2,type:T.EXHAUST_OFF,metadata:'A,B'});q.tasks.push(task);expect(q.find({time:2})).toBeUndefined();expect(q.find({time:2,comparison:'>'})).toBeUndefined();expect(q.find({time:2+1.4/3600,comparison:'=',metadata:'B'})).toBe(task);expect(q.find({time:2+1.5/3600,comparison:'='})).toBeUndefined();expect(q.find({type:T.SHIFT_OFF})).toBeUndefined()})
 it('consumes object identity even when another task has equal type plan and time',()=>{const q=new MowerTaskQueue(),a=new MowerTask({time:2,type:T.SHIFT_ON,plan:{room:['A']}}),b=new MowerTask({time:2,type:T.SHIFT_ON,plan:{room:['A']}});expect(a.equals(b)).toBe(true);q.tasks.push(a,b,a);q.consume(a);expect(q.tasks).toEqual([b])})
 it('does not clone the plan object reserved by resting()',()=>{const plan={room:['A']},t=new MowerTask({time:0,type:T.SHIFT_OFF,plan});plan.room[0]='B';expect(t.plan).toBe(plan);expect(t.plan.room).toEqual(['B'])})
 it('retains non-derived future and current tasks while rebuilding ordinary metadata',()=>{const q=new MowerTaskQueue(),off=new MowerTask({time:0,type:T.SHIFT_OFF}),noop=new MowerTask({time:2.5}),fia=new MowerTask({time:3,type:T.FIAMMETTA}),on=new MowerTask({time:4,type:T.SHIFT_ON}),release=new MowerTask({time:5,type:T.RELEASE_DORM});q.tasks.push(off,noop,fia,on,release);q.removeDerived();expect(q.tasks).toEqual([off,noop,fia])})
 it('creates a fallback only if no queued task is strictly before now plus 2.5h',()=>{const q=new MowerTaskQueue();const initial=q.ensureFallback(0);expect(initial?.time).toBe(2.5);q.tasks.push(new MowerTask({time:2,type:T.FIAMMETTA}));expect(q.ensureFallback(1)).toBeUndefined();expect(q.tasks[0]).toBe(initial);q.consume(q.tasks[1]!);expect(q.ensureFallback(2)).toBeUndefined();expect(initial?.time).toBe(2.5);q.consume(initial!);expect(q.ensureFallback(2.5)?.time).toBe(5)})
 it('also suppresses fallback for a future non-roster queued task',()=>{const q=new MowerTaskQueue();q.tasks.push(new MowerTask({time:1,type:T.WORKSHOP}));expect(q.ensureFallback(0)).toBeUndefined()})
 it('keeps source microsecond backup anchors distinct',()=>{const t=new MowerTask({time:2});const t0=toMowerMicros(2);t.timeMicros=t0-1;expect(t.timeMicros).toBe(t0-1);expect(t.time).toBeLessThan(2)})
})

it('rounds fractional microseconds as Python timedelta with ties to even',()=>{expect(toMowerMicros(.5/3_600_000_000)).toBe(0);expect(toMowerMicros(2.5/3_600_000_000)).toBe(2);expect(toMowerMicros(-.5/3_600_000_000)).toBe(0);expect(toMowerMicros(-2.5/3_600_000_000)).toBe(-2)})
