import {describe,it,expect} from 'vitest'
import {MowerOperatorState,restingMood,hasRestingMood,mowerReplacementCandidates} from './mowerOperatorState'
import {toMowerMicros} from './mowerTaskQueue'
describe('pinned Mower observed operator state',()=>{
 it('keeps the original cached mood when prediction crosses the physical endpoints',()=>{const op=new MowerOperatorState({name:'A',mood:2,timeStampMicros:0,depletionRate:1});expect(op.currentMood(toMowerMicros(1))).toBe(1);expect(op.currentMood(toMowerMicros(3))).toBe(2)})
 it('distinguishes unknown default mood from an actual observation',()=>{const op=new MowerOperatorState({name:'R',mood:0});expect(hasRestingMood(op,0)).toBe(false);expect(restingMood(op,0)).toBe(24);op.timeStampMicros=0;expect(hasRestingMood(op,0)).toBe(true);expect(restingMood(op,0)).toBe(0)})
 it('uses the observed timestamp and real exhaust clock in rescue prediction',()=>{const op=new MowerOperatorState({name:'A',mood:4,lowerLimit:1,timeStampMicros:toMowerMicros(1),depletionRate:2,exhaustTimeMicros:toMowerMicros(1.75)});expect(op.predictExhaust(toMowerMicros(1.5))).toBe(toMowerMicros(1.75));op.exhaustTimeMicros=undefined;expect(op.predictExhaust(toMowerMicros(1.5))).toBe(toMowerMicros(2))})
 it.each([{workaholic:true},{exhaustRequire:true},{room:'factory'},{room:'train'}])('excludes the original special case %j from rescue prediction',extra=>{const op=new MowerOperatorState({name:'A',mood:0,timeStampMicros:0,depletionRate:1,...extra});expect(op.predictExhaust(toMowerMicros(3))).toBe(toMowerMicros(27))})
 it('defers a known emergency-low cover but keeps unknown and normal original order',()=>{const a=new MowerOperatorState({name:'A',room:'room_1_1',replacement:['R','Y','Z']});const r=new MowerOperatorState({name:'R',mood:0,timeStampMicros:0}),y=new MowerOperatorState({name:'Y',mood:24,timeStampMicros:0}),z=new MowerOperatorState({name:'Z',mood:0});const ops={A:a,R:r,Y:y,Z:z};expect(mowerReplacementCandidates(a,ops,{restingThreshold:.65,rescueThreshold:.75},0)).toEqual(['Y','Z','R']);r.timeStampMicros=undefined;expect(mowerReplacementCandidates(a,ops,{restingThreshold:.65,rescueThreshold:.75},0)).toEqual(['R','Y','Z'])})
 it('keeps Fiammetta target order and sorts grouped dorm covers by known mood',()=>{const r=new MowerOperatorState({name:'R',mood:10,timeStampMicros:0}),y=new MowerOperatorState({name:'Y',mood:3,timeStampMicros:0}),z=new MowerOperatorState({name:'Z',mood:0});const ops={R:r,Y:y,Z:z},policy={restingThreshold:.65,rescueThreshold:.75};const fia=new MowerOperatorState({name:'F',nativeName:'菲亚梅塔',room:'dormitory_1',replacement:['R','Y','Z']});expect(mowerReplacementCandidates(fia,ops,policy,0)).toEqual(['R','Y','Z']);const dorm=new MowerOperatorState({name:'D',room:'dormitory_1',group:'g',replacement:['R','Y','Z']});expect(mowerReplacementCandidates(dorm,ops,policy,0)).toEqual(['Y','R','Z'])})
})
