/** @vitest-environment jsdom */
import {describe,it,expect,vi,afterEach} from 'vitest'
import {mount} from '@vue/test-utils'
import {createDefaultWorkspace} from '../../workbench/defaults'
import ScheduleSimulationPanel from './ScheduleSimulationPanel.vue'
import {captureOrder,getOrderDistribution} from '../../rules/orderRules'
const instances:any[]=[]
it('ignores saved physical run-order settings and offers only ideal run-order',async()=>{
 localStorage.setItem('riic-mower-simulation-settings-v1',JSON.stringify({runOrderMode:'grandet',runOrderLeadSeconds:90,runOrderBufferSeconds:-1}))
 vi.stubGlobal('Worker',MockWorker)
 const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}})
 expect(w.find('[data-test=run-order-mode]').exists()).toBe(false)
 expect(w.find('[data-test=run-order-lead]').exists()).toBe(false)
 expect(w.find('[data-test=run-order-buffer]').exists()).toBe(false)
 expect(w.text()).not.toContain('葛朗台')
 await w.get('[data-test=simulate-schedule]').trigger('click')
 expect(instances[0].postMessage.mock.calls[0][0].options.production).toMatchObject({runOrderMode:'ideal'})
 expect(instances[0].postMessage.mock.calls[0][0].options.production).not.toHaveProperty('runOrderLeadSeconds')
 expect(instances[0].postMessage.mock.calls[0][0].options.production).not.toHaveProperty('runOrderBufferSeconds')
 const saved=JSON.parse(localStorage.getItem('riic-mower-simulation-settings-v1')!)
 expect(saved).not.toHaveProperty('runOrderMode')
 expect(saved).not.toHaveProperty('runOrderLeadSeconds')
 expect(saved).not.toHaveProperty('runOrderBufferSeconds')
 w.unmount()
})
class MockWorker {onmessage:any;onerror:any;postMessage=vi.fn();terminate=vi.fn();constructor(){instances.push(this)}}
afterEach(()=>{vi.unstubAllGlobals();instances.length=0;localStorage.removeItem('riic-mower-simulation-settings-v1')})
describe('schedule simulation panel',()=>{
 it('uses the full catalog without an imported idle library',async()=>{
  vi.stubGlobal('Worker',MockWorker)
  const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}})
  await w.get('[data-test=simulate-schedule]').trigger('click')
  const sent=instances[0].postMessage.mock.calls[0][0]
  expect(sent.options).not.toHaveProperty('operatorInventory')
  expect(sent.assumptions).not.toHaveProperty('idleOperators')
  expect(w.text()).toContain('未导入干员库时从全体干员中选择')
  w.unmount()
 })
 it('runs in a worker, keeps defaults visible, and cancels stale work when roster changes',async()=>{
  vi.stubGlobal('Worker',MockWorker)
  const ws=createDefaultWorkspace(),w=mount(ScheduleSimulationPanel,{props:{workspace:ws}})
  expect(w.get('[data-test=sample-days]').element).toHaveProperty('value','14')
  await w.get('[data-test=simulate-schedule]').trigger('click')
  expect(instances[0].postMessage.mock.calls[0][0].options).toMatchObject({sampleHours:336,warmupHours:168})
  expect(w.text()).toContain('取消')
  await w.setProps({workspace:{...ws,name:'changed'}})
  expect(instances[0].terminate).toHaveBeenCalled();expect(w.text()).not.toContain('取消模拟')
  instances[0].onmessage({data:{error:'已取消的旧结果'}});await w.vm.$nextTick();expect(w.text()).not.toContain('已取消的旧结果')
  w.unmount()
 })
 it('surfaces worker failures rather than showing a completed estimate',async()=>{
  vi.stubGlobal('Worker',MockWorker)
  const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}})
  await w.get('[data-test=simulate-schedule]').trigger('click')
  instances[0].onmessage({data:{error:'缺少当前干员状态'}})
  await w.vm.$nextTick();expect(w.text()).toContain('缺少当前干员状态');w.unmount()
 })
})
it('defaults to ideal run-order without physical temporary staffing',async()=>{vi.stubGlobal('Worker',MockWorker);const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}});expect(w.get('h2').text()).toBe('心情与产出模拟');await w.get('[data-test=simulate-schedule]').trigger('click');expect(instances[0].postMessage.mock.calls[0][0].options.production).toEqual({outputMode:'potential',inventoryMode:'unlimited',runOrderMode:'ideal',droneTarget:'gold',initialResources:{drone:0},seed:1,collectionIntervalHours:0});expect(w.text()).toContain('不执行临时换人或跑单等待');w.unmount()})
it('sends changed production controls and rejects invalid initial amounts before starting a worker',async()=>{vi.stubGlobal('Worker',MockWorker);const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}});await w.get('[data-test=output-mode]').setValue('settled');await w.get('[data-test=inventory-mode]').setValue('finite');expect(w.find('[data-test=run-order-mode]').exists()).toBe(false);await w.get('[data-test=drone-target]').setValue('exp');await w.get('[data-test=initial-gold]').setValue('20');await w.get('[data-test=initial-device]').setValue('3');await w.get('[data-test=collection-interval]').setValue('2');await w.get('[data-test=production-seed]').setValue('42');await w.get('[data-test=simulate-schedule]').trigger('click');expect(instances[0].postMessage.mock.calls[0][0].options.production).toMatchObject({runOrderMode:'ideal',droneTarget:'exp',initialResources:{gold:20,device:3},seed:42,collectionIntervalHours:0});await w.get('[data-test=initial-gold]').setValue('-1');expect(instances[0].terminate).toHaveBeenCalled();await w.get('[data-test=simulate-schedule]').trigger('click');expect(instances).toHaveLength(1);expect(w.get('[role=alert]').text()).toContain('初始库存');w.unmount()})
it('shows sample resource movements and distinguishes incomplete production from a completed window',async()=>{vi.stubGlobal('Worker',MockWorker);const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}});await w.get('[data-test=simulate-schedule]').trigger('click');instances[0].onmessage({data:{report:{success:true,observedHours:24,rooms:[],operators:[],diagnostics:[{code:'PENDING',message:'订单条件尚未完整量化'}],production:{success:false,sample:{opening:{gold:10},closing:{gold:13},inflows:{gold:8,exp:1000},outflows:{gold:5},net:{gold:3,exp:1000}},drones:{stock:12,capacity:235},manufacturing:[{completedItems:999999}],trading:[]}}}});await w.vm.$nextTick();expect(w.text()).toContain('模拟窗口已完成');expect(w.text()).toContain('产出策略未完整执行');expect(w.text()).toContain('EXP 点数');expect(w.get('[data-test=production-gold]').text()).toContain('+3');expect(w.text()).not.toContain('999999');expect(w.text()).toContain('期末无人机');w.unmount()})
it('labels completed production separately and retains exports for a result',async()=>{vi.stubGlobal('Worker',MockWorker);const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}});await w.get('[data-test=simulate-schedule]').trigger('click');instances[0].onmessage({data:{report:{success:true,observedHours:336,rooms:[],operators:[],diagnostics:[],production:{success:true,sample:{opening:{},closing:{},inflows:{},outflows:{},net:{}},drones:{stock:0,capacity:235}}}}});await w.vm.$nextTick();expect(w.text()).toContain('产出计算窗口已完成');expect(w.text()).toContain('导出明细 JSON');expect(w.findAll('[data-test^=production-]').length).toBeGreaterThan(0);w.unmount()})

it('passes owned stages into the worker and invalidates old results on inventory edits',async()=>{
 localStorage.clear();vi.stubGlobal('Worker',MockWorker)
 const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}})
 await w.get('[data-test=inventory-enabled]').setValue(true)
 await w.get('[data-test=inventory-text]').setValue('砾,1,1')
 await w.get('[data-test=simulate-schedule]').trigger('click')
 expect(instances[0].postMessage.mock.calls[0][0].options.operatorInventory).toEqual([{operator:'砾',elitePhase:1,level:1}])
 await w.get('[data-test=inventory-text]').setValue('砾')
 expect(instances[0].terminate).toHaveBeenCalled()
 await w.get('[data-test=simulate-schedule]').trigger('click')
 expect(instances).toHaveLength(1)
 expect(w.get('[role=alert]').text()).toContain('干员库')
 w.unmount();localStorage.clear()
})

it('removes completed reports on inventory changes and ignores a late worker message',async()=>{
 localStorage.clear();vi.stubGlobal('Worker',MockWorker)
 const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}})
 await w.get('[data-test=simulate-schedule]').trigger('click')
 const completed={report:{success:true,observedHours:24,rooms:[],operators:[],diagnostics:[]}}
 instances[0].onmessage({data:completed});await w.vm.$nextTick()
 expect(w.text()).toContain('模拟窗口已完成')
 await w.get('[data-test=inventory-enabled]').setValue(true)
 expect(w.text()).not.toContain('模拟窗口已完成')
 instances[0].onmessage({data:completed});await w.vm.$nextTick()
 expect(w.text()).not.toContain('模拟窗口已完成')
 w.unmount();localStorage.clear()
})

it('runs the generated draft in the worker while retaining the manual workspace',async()=>{
 localStorage.clear();vi.stubGlobal('Worker',MockWorker)
 const workspace=createDefaultWorkspace(),w=mount(ScheduleSimulationPanel,{props:{workspace}})
 await w.get('[data-test=inventory-enabled]').setValue(true)
 await w.get('[data-test=inventory-text]').setValue('温蒂,2,1\n清流,1,1')
 await w.get('[data-candidate=manu-gold-weedy-purestream]').setValue(true)
 await w.get('[data-test=generate-draft]').trigger('click')
 await w.get('[data-test=simulate-draft]').trigger('click')
 const sent=instances[0].postMessage.mock.calls[0][0]
 expect(sent.workspace.mainPlan.facilities.room_1_1.slots.filter((s:any)=>s.occupant.kind==='operator')).toHaveLength(2)
 expect(workspace.mainPlan.facilities.room_1_1.slots.every(s=>s.occupant.kind==='empty')).toBe(true)
 instances[0].onmessage({data:{report:{success:true,observedHours:24,rooms:[],operators:[],diagnostics:[]}}});await w.vm.$nextTick()
 expect(w.text()).toContain('组合草案')
 await w.get('[data-candidate=manu-gold-weedy-purestream]').setValue(false)
 expect(w.text()).not.toContain('模拟窗口已完成')
 w.unmount();localStorage.clear()
})


it('renders completed output with the user weights and clears it when output mode changes',async()=>{
 vi.stubGlobal('Worker',MockWorker);const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}})
 await w.get('[data-test=simulate-schedule]').trigger('click')
 instances[0].onmessage({data:{report:{success:true,observedHours:24,rooms:[],operators:[],diagnostics:[],production:{success:true,assumptions:{outputMode:'potential'},sample:{completed:{exp:1000,gold:2,orderLmd:1500}},drones:{stock:0,capacity:235}}}}})
 await w.vm.$nextTick();expect(w.get('[data-test=completed-production-score]').text()).toContain('2,100');expect(w.text()).not.toContain('期初库存包含预热结余')
 await w.get('[data-test=output-mode]').setValue('settled');expect(w.find('[data-test=completed-production-score]').exists()).toBe(false);w.unmount()
})


it.each([[false,true],[true,false]])('does not label an incomplete result as daily production (%s/%s)',async(success,productionSuccess)=>{
 vi.stubGlobal('Worker',MockWorker)
 const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}})
 await w.get('[data-test=simulate-schedule]').trigger('click')
 instances[0].onmessage({data:{report:{success,observedHours:24,rooms:[],operators:[],diagnostics:[],production:{success:productionSuccess,assumptions:{outputMode:'potential'},sample:{completed:{exp:1000,gold:2,orderLmd:1500}},drones:{stock:0,capacity:235}}}}})
 await w.vm.$nextTick()
 const label=w.get('[data-test=completed-production-score]').text()
 expect(label).toContain('2,100')
 expect(label).toContain('不可作为日均结论')
 expect(label).not.toContain('每日综合产出')
 w.unmount()
})

it('sends and retains the selected global Mower settings across remounts',async()=>{
 vi.stubGlobal('Worker',MockWorker)
 const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}})
 await w.get('[data-test=resting-threshold]').setValue(67.5)
 await w.get('[data-test=fiammetta-fool]').setValue(false)
 await w.get('[data-test=fiammetta-threshold]').setValue(80)
 await w.get('[data-test=rescue-threshold]').setValue(90)
 await w.get('[data-test=free-room]').setValue(true)
 await w.get('[data-test=simulate-schedule]').trigger('click')
 expect(instances[0].postMessage.mock.calls[0][0].assumptions).toMatchObject({restingThreshold:.675,fiammettaFool:false,fiammettaThreshold:.8,rescueThreshold:.9,freeRoom:true})
 w.unmount()
 const restored=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}})
 expect(restored.get('[data-test=resting-threshold]').element).toHaveProperty('value','67.5')
 expect(restored.get('[data-test=fiammetta-fool]').element).toHaveProperty('checked',false)
 expect(restored.get('[data-test=fiammetta-threshold]').element).toHaveProperty('value','80')
 expect(restored.get('[data-test=rescue-threshold]').element).toHaveProperty('value','90')
 expect(restored.get('[data-test=free-room]').element).toHaveProperty('checked',true)
 restored.unmount()
})
it('does not present unresolved shift deferrals as stable daily output',async()=>{
 vi.stubGlobal('Worker',MockWorker)
 const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}})
 await w.get('[data-test=simulate-schedule]').trigger('click')
 instances[0].onmessage({data:{report:{success:true,observedHours:24,rooms:[],operators:[],diagnostics:[{code:'group-blocked',message:'group:g: blocked'}],production:{success:true,assumptions:{outputMode:'potential'},sample:{completed:{exp:1000,gold:2,orderLmd:1500}},drones:{stock:0,capacity:235}}}}})
 await w.vm.$nextTick()
 expect(w.get('[data-test=roster-deferred]').text()).toContain('换班延后')
 expect(w.get('[data-test=completed-production-score]').text()).toContain('不可作为稳定日均结论')
 w.unmount()
})

it('keeps malformed production reports reviewable without inventing a score or crashing',async()=>{
 vi.stubGlobal('Worker',MockWorker)
 const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}})
 await w.get('[data-test=simulate-schedule]').trigger('click')
 instances[0].onmessage({data:{report:{success:true,observedHours:24,rooms:[],operators:[],diagnostics:[],production:{success:true,assumptions:{outputMode:'potential'},sample:{},drones:{stock:0,capacity:235}}}}})
 await w.vm.$nextTick()
 expect(w.find('[data-test=completed-production-score]').exists()).toBe(false)
 expect(w.get('[data-test=production-score-unavailable]').text()).toContain('缺少可用的完成产出数据')
 expect(w.text()).toContain('导出明细 JSON')
 expect(w.text()).not.toContain('NaN')
 w.unmount()
})

it('renders a complete report with frozen user weights, virtual gold and fragments',async()=>{
 vi.stubGlobal('Worker',MockWorker)
 const w=mount(ScheduleSimulationPanel,{props:{workspace:createDefaultWorkspace()}})
 await w.get('[data-test=simulate-schedule]').trigger('click')
 const productionWeights={exp:2,gold:.8,orders:.2,fragments:5,orundum:0}
 const order=captureOrder(getOrderDistribution(3,'normal','closure')[0]!,{closure:true},12)
 instances[0].onmessage({data:{report:{success:true,observedHours:24,elapsedHours:24,assumptions:{warmupHours:0},inputs:{options:{productionWeights}},rooms:[],operators:[],diagnostics:[],production:{success:true,assumptions:{outputMode:'potential'},sample:{completed:{exp:1000,gold:2,orderLmd:1200}},events:[{type:'order-completed',time:12,order}],manufacturing:[{product:'fragment',sampleCompletedItems:3}],drones:{stock:0,capacity:235}}}}})
 await w.vm.$nextTick()
 const score=w.get('[data-test=completed-production-score]').text()
 expect(score).toContain('每日加权产出：3,215')
 expect(score).toContain('960 赤金及虚拟赤金贡献')
 expect(score).toContain('15 碎片贡献')
 expect(w.find('[data-test=production-score-unavailable]').exists()).toBe(false)
 w.unmount()
})
